'use strict';

module.exports = Object.freeze({
	GET_TRENDING: 'GET_TRENDING',
	TRENDING_RESULT: 'TRENDING_RESULT',
	GET_SEARCH: 'GET_SEARCH',
	SEARCH_RESULT: 'SEARCH_RESULT',
	ERROR: 'ERROR',
	ADD_GENRE: 'ADD_GENRE',
	REMOVE_GENRE: 'REMOVE_GENRE',
	SAVE_PLAYLIST: 'SAVE_PLAYLIST',
	ADD_TO_PLAYLIST: 'ADD_TO_PLAYLIST'
	});